name: SSH Warpify Issues? Use this template
description: "Issue template specialized for the circumstances where SSH Warpification with tmux fails"
labels: ["bug","area:ssh"]
body:
  - type: checkboxes
    attributes:
      label: "Pre-submit Checks"
      options:
        - label: "I have searched existing local-first fork SSH issues and there are no duplicates"
          required: true
        - label: "I have included local logs when they are relevant and redacted personal details."
          required: false    
  - type: textarea
    id: "shell-output"
    attributes:
      label: "Include shell output"
      description: "Click on the top right icon of your terminal block, select `Copy`, and paste the contents here. Please redact any personal details."
      render: shell
    validations:
      required: true
  - type: textarea
    id: "screenshots-logs"
    attributes:
      label: "Screenshots, videos, and logs"
      description: "If applicable, add screenshots/videos/logs to help us understand your problem. While optional, these help expedite the time in which your bug is addressed."
    validations:
      required: false      
  - type: dropdown
    id: "os"
    attributes:
      label: "Operating system (OS)"
      multiple: false
      options:
        - "Select an OS"
        - macOS
        - Linux
        - Windows
    validations:
      required: true
  - type: input
    id: "os-version"
    attributes:
      label: "Operating system and version"
      description: "For example: Debian 11.2"
    validations:
      required: true
  - type: input
    id: "warp-version"
    attributes:
      label: "Warp Version"
      description: "Warp Version"
    validations:
      required: false
